export const BRANDS = ['All', 'Apple', 'Samsung', 'Google', 'HTC'];

export const ecommerceProducts = [
  {
    id: 1,
    title: 'Google Pixel - Black',
    img: 'img/product-1.png',
    price: 649,
    originalPrice: 749,
    company: 'google',
    category: 'Flagship',
    rating: 4.5,
    reviews: 128,
    featured: true,
    inStock: true,
    specs: {
      display: '5.0" AMOLED',
      storage: '128 GB',
      camera: '12.3 MP',
      battery: '2770 mAh',
    },
    info:
      'Pure Android experience with the best smartphone camera of its generation. Night Sight, unlimited Google Photos backup, and fast charging make this a standout flagship.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: 'Samsung Galaxy S7',
    img: 'img/product-2.png',
    price: 599,
    originalPrice: 699,
    company: 'samsung',
    category: 'Flagship',
    rating: 4.3,
    reviews: 256,
    featured: true,
    inStock: true,
    specs: {
      display: '5.1" Super AMOLED',
      storage: '32 GB',
      camera: '12 MP',
      battery: '3000 mAh',
    },
    info:
      'Water-resistant design meets premium glass and metal build. Always-on display, expandable storage, and wireless charging in a compact flagship form factor.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: 'HTC 10 - Black',
    img: 'img/product-3.png',
    price: 499,
    company: 'htc',
    category: 'Flagship',
    rating: 4.1,
    reviews: 89,
    featured: false,
    inStock: true,
    specs: {
      display: '5.2" QHD',
      storage: '32 GB',
      camera: '12 MP',
      battery: '3000 mAh',
    },
    info:
      'BoomSound Hi-Fi audio and a sleek aluminum unibody. Snapdragon 820 performance with HTC Sense UI tuned for speed and simplicity.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: 'HTC 10 - White',
    img: 'img/product-4.png',
    price: 519,
    company: 'htc',
    category: 'Flagship',
    rating: 4.2,
    reviews: 64,
    featured: false,
    inStock: true,
    specs: {
      display: '5.2" QHD',
      storage: '32 GB',
      camera: '12 MP',
      battery: '3000 mAh',
    },
    info:
      'Same award-winning HTC 10 hardware in a stunning white finish. Premium audio, fast fingerprint sensor, and all-day battery life.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: 'HTC Desire 626s',
    img: 'img/product-5.png',
    price: 199,
    originalPrice: 249,
    company: 'htc',
    category: 'Mid-range',
    rating: 3.8,
    reviews: 42,
    featured: false,
    inStock: true,
    specs: {
      display: '5.0" HD',
      storage: '16 GB',
      camera: '13 MP',
      battery: '2000 mAh',
    },
    info:
      'Affordable everyday smartphone with a vibrant display and reliable performance. Perfect as a backup phone or first smartphone.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: 'Vintage iPhone',
    img: 'img/product-6.png',
    price: 89,
    company: 'apple',
    category: 'Classic',
    rating: 4.0,
    reviews: 312,
    featured: false,
    inStock: true,
    specs: {
      display: '3.5" Retina',
      storage: '16 GB',
      camera: '5 MP',
      battery: '1420 mAh',
    },
    info:
      'A collector favorite — the phone that changed everything. Fully functional vintage piece for enthusiasts and nostalgia lovers.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: 'iPhone 7',
    img: 'img/product-7.png',
    price: 449,
    originalPrice: 549,
    company: 'apple',
    category: 'Flagship',
    rating: 4.4,
    reviews: 521,
    featured: true,
    inStock: true,
    specs: {
      display: '4.7" Retina HD',
      storage: '32 GB',
      camera: '12 MP',
      battery: '1960 mAh',
    },
    info:
      'Iconic Apple design with A10 Fusion chip, water resistance, and stereo speakers. Still a capable daily driver with iOS support.',
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: 'Refurbished iPhone (As-Is)',
    img: 'img/product-8.png',
    price: 49,
    company: 'apple',
    category: 'Budget',
    rating: 2.5,
    reviews: 18,
    featured: false,
    inStock: true,
    specs: {
      display: '4.0" LCD',
      storage: '8 GB',
      camera: '5 MP',
      battery: '1400 mAh',
    },
    info:
      'Budget pick for parts or display purposes. Sold as-is with visible wear — great for DIY repairs or prop use. No returns.',
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = { ...ecommerceProducts[0] };
